//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustTransaction
    {
        public int Tranid { get; set; }
        public Nullable<int> Custid { get; set; }
        public Nullable<System.DateTime> tranDate { get; set; }
        public Nullable<decimal> Amt { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
