//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SomeBankEntities1 : DbContext
    {
        public SomeBankEntities1()
            : base("name=SomeBankEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASPStateTempApplication> ASPStateTempApplications { get; set; }
        public virtual DbSet<ASPStateTempSession> ASPStateTempSessions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustTransaction> CustTransactions { get; set; }
        public virtual DbSet<TransferMoney> TransferMoneys { get; set; }
    
        [DbFunction("SomeBankEntities1", "fn_ShowTransactionHistory")]
        public virtual IQueryable<fn_ShowTransactionHistory_Result> fn_ShowTransactionHistory(Nullable<int> p_custid)
        {
            var p_custidParameter = p_custid.HasValue ?
                new ObjectParameter("p_custid", p_custid) :
                new ObjectParameter("p_custid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_ShowTransactionHistory_Result>("[SomeBankEntities1].[fn_ShowTransactionHistory](@p_custid)", p_custidParameter);
        }
    
        public virtual int sp_TransferMoney(Nullable<int> p_custidFrom, Nullable<int> p_custidTo, Nullable<decimal> p_amt)
        {
            var p_custidFromParameter = p_custidFrom.HasValue ?
                new ObjectParameter("p_custidFrom", p_custidFrom) :
                new ObjectParameter("p_custidFrom", typeof(int));
    
            var p_custidToParameter = p_custidTo.HasValue ?
                new ObjectParameter("p_custidTo", p_custidTo) :
                new ObjectParameter("p_custidTo", typeof(int));
    
            var p_amtParameter = p_amt.HasValue ?
                new ObjectParameter("p_amt", p_amt) :
                new ObjectParameter("p_amt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TransferMoney", p_custidFromParameter, p_custidToParameter, p_amtParameter);
        }
    
        public virtual int ValidateUser(string p_username, string p_pwd, ObjectParameter p_userStatus, ObjectParameter p_custname)
        {
            var p_usernameParameter = p_username != null ?
                new ObjectParameter("p_username", p_username) :
                new ObjectParameter("p_username", typeof(string));
    
            var p_pwdParameter = p_pwd != null ?
                new ObjectParameter("p_pwd", p_pwd) :
                new ObjectParameter("p_pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ValidateUser", p_usernameParameter, p_pwdParameter, p_userStatus, p_custname);
        }
    }
}
