//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferMoney
    {
        public int tranid { get; set; }
        public Nullable<System.DateTime> tranDate { get; set; }
        public Nullable<int> custidFrom { get; set; }
        public Nullable<int> custidTo { get; set; }
        public Nullable<decimal> Amt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
